# Generated by Django 2.2.5 on 2019-09-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_autor', models.IntegerField()),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entrada', models.IntegerField()),
                ('titular', models.CharField(max_length=120)),
                ('fecha_hora', models.CharField(max_length=120)),
                ('contenido', models.TextField()),
                ('autor', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Autor')),
            ],
        ),
    ]
