# Generated by Django 2.2.5 on 2019-09-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='id',
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_autor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Autor'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='id_entrada',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
